### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by terrykong** [NVIDIA/JAX-Toolbox#134]
This issue is to track items related to producing and testing ARM images in JAX-Toolbox

```[tasklist]
### Tasks
- [x] (build) JAX ARM image
- [ ] (test) JAX ARM image
- [x] (build) t5x ARM image
- [ ] (test)  t5x ARM image
- [x] (build) pax ARM image
- [ ] (test) pax ARM image
```

**Comment by nouiz** [comment]
All done
